// AUTO-GENERATED by `pnpm db:types` (supabase gen types typescript --linked).
// Do not hand-edit. Regenerate after every migration (see AGENTS.md).
//
// Placeholder until Phase 0.2 migrations exist and a Supabase project is
// linked. Replace by running `pnpm db:types` once `supabase link` has been
// run against the project's Supabase instance.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: Record<string, never>;
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
}
